source 'https://bitbucket.org/compec/mambospecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MamboSerialization_Example' do
    pod 'MamboSerialization', :path => '../'
    
    target 'MamboSerialization_Tests' do
        inherit! :search_paths
        
        pod 'Specta'
        pod 'Expecta'
        pod 'FBSnapshotTestCase'
        pod 'Expecta+Snapshots'
    end
end
